import React, { useState } from 'react';
import { X, Sparkles, User, Calendar, MapPin, ArrowRight, Clock, Phone, Mail, CheckCircle2 } from 'lucide-react';

interface IncomingLeadsModalProps {
  isOpen: boolean;
  onClose: () => void;
  leads: any[];
  onSelectLead: (lead: any) => void;
  linkedInquiryId: string | null;
  isDarkMode?: boolean;
}

export const IncomingLeadsModal: React.FC<IncomingLeadsModalProps> = ({
  isOpen,
  onClose,
  leads,
  onSelectLead,
  linkedInquiryId,
  isDarkMode = false
}) => {
  const [searchTerm, setSearchTerm] = useState('');

  if (!isOpen) return null;

  const filteredLeads = leads.filter(l => {
    const q = searchTerm.toLowerCase();
    const name = (l.userName || '').toLowerCase();
    const email = (l.userEmail || '').toLowerCase();
    const plan = (l.planTitle || '').toLowerCase();
    const interests = (l.formData?.interests || '').toLowerCase();
    return name.includes(q) || email.includes(q) || plan.includes(q) || interests.includes(q);
  });

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs animate-fadeIn">
      <div 
        className={`w-full max-w-3xl rounded-3xl border shadow-2xl flex flex-col max-h-[85vh] overflow-hidden ${
          isDarkMode ? 'bg-[#111928] border-slate-800 text-white' : 'bg-white border-gray-200 text-gray-900'
        }`}
      >
        {/* Modal Header */}
        <div className="p-6 border-b border-gray-100 dark:border-slate-800/80 flex items-center justify-between shrink-0">
          <div className="flex items-center space-x-3">
            <div className="p-2.5 bg-gradient-to-tr from-orange-500 to-amber-500 text-white rounded-2xl shadow-md shadow-orange-500/20">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-base font-extrabold flex items-center gap-2">
                Incoming AI Trip Planner Leads
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-orange-500/10 text-orange-600 dark:text-orange-400 font-black">
                  {leads.length} Live
                </span>
              </h2>
              <p className="text-xs text-gray-500">
                Itineraries generated by website visitors converted into official proposals with 1-click
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-2 text-gray-400 hover:text-gray-700 dark:hover:text-gray-200 rounded-xl hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Search Bar */}
        <div className="p-4 border-b border-gray-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/50">
          <input
            type="text"
            placeholder="Search by traveler name, email, or interests..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className={`w-full px-4 py-2.5 text-xs rounded-xl border focus:outline-none focus:ring-2 focus:ring-orange-500/30 transition-all ${
              isDarkMode 
                ? 'bg-slate-800 border-slate-700 text-white placeholder:text-gray-500' 
                : 'bg-white border-gray-200 text-gray-900 placeholder:text-gray-400'
            }`}
          />
        </div>

        {/* Leads List */}
        <div className="p-6 overflow-y-auto space-y-4 flex-1">
          {filteredLeads.length === 0 ? (
            <div className="text-center py-12 space-y-3">
              <div className="w-12 h-12 rounded-2xl bg-orange-500/10 text-orange-500 flex items-center justify-center mx-auto">
                <Sparkles className="w-6 h-6" />
              </div>
              <h3 className="text-sm font-bold">No AI Planner inquiries found</h3>
              <p className="text-xs text-gray-400 max-w-sm mx-auto">
                When website visitors craft custom trips using the AI Trip Planner, their plans, party size, and contacts will stream in here live.
              </p>
            </div>
          ) : (
            filteredLeads.map((lead) => {
              const isLinked = linkedInquiryId === lead.id;
              const days = lead.itinerary?.dailyPlans?.length || lead.itinerary?.days?.length || lead.formData?.duration || 3;
              const persons = lead.formData?.persons || '2 Persons';
              const createdDate = lead.createdAt?.toDate 
                ? lead.createdAt.toDate().toLocaleDateString('en-US', { month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit' })
                : 'Recent';

              return (
                <div
                  key={lead.id}
                  className={`p-4 rounded-2xl border transition-all hover:shadow-md ${
                    isLinked
                      ? 'border-orange-500 bg-orange-500/5 ring-1 ring-orange-500'
                      : isDarkMode
                      ? 'bg-slate-900/80 border-slate-800 hover:border-slate-700'
                      : 'bg-white border-gray-200 hover:border-orange-300'
                  }`}
                >
                  <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
                    <div className="space-y-1.5 flex-1 min-w-0">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-extrabold text-sm text-gray-900 dark:text-white truncate">
                          {lead.userName || 'Anonymous Traveler'}
                        </span>
                        {lead.status && (
                          <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full ${
                            lead.status === 'proposal_sent'
                              ? 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20'
                              : 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20'
                          }`}>
                            {lead.status === 'proposal_sent' ? 'Proposal Created' : 'New Lead'}
                          </span>
                        )}
                        {isLinked && (
                          <span className="text-[10px] font-black px-2 py-0.5 rounded-full bg-orange-500 text-white flex items-center gap-1">
                            <CheckCircle2 className="w-3 h-3" />
                            <span>Currently Active in Studio</span>
                          </span>
                        )}
                      </div>

                      <p className="text-xs font-semibold text-orange-600 dark:text-orange-400">
                        {lead.planTitle || `${days}-Day Custom Travel Plan`}
                      </p>

                      <div className="flex items-center gap-4 text-[11px] text-gray-500 dark:text-gray-400 flex-wrap">
                        {lead.userEmail && (
                          <span className="flex items-center gap-1">
                            <Mail className="w-3 h-3" />
                            {lead.userEmail}
                          </span>
                        )}
                        {lead.userPhone && (
                          <span className="flex items-center gap-1">
                            <Phone className="w-3 h-3" />
                            {lead.userPhone}
                          </span>
                        )}
                        <span className="flex items-center gap-1">
                          <Clock className="w-3 h-3" />
                          {days} Days • {persons}
                        </span>
                        <span className="text-gray-400">Received {createdDate}</span>
                      </div>

                      {lead.summary && (
                        <p className="text-xs text-gray-600 dark:text-gray-300 line-clamp-2 pt-1">
                          "{lead.summary}"
                        </p>
                      )}
                    </div>

                    <div className="shrink-0 self-start sm:self-center">
                      <button
                        type="button"
                        onClick={() => onSelectLead(lead)}
                        className={`px-4 py-2 rounded-xl font-bold text-xs flex items-center space-x-1.5 transition-all cursor-pointer shadow-xs ${
                          isLinked
                            ? 'bg-gray-200 dark:bg-slate-800 text-gray-700 dark:text-gray-300'
                            : 'bg-gradient-to-r from-orange-500 to-amber-500 text-white hover:from-orange-600 hover:to-amber-600 hover:shadow-orange-500/20'
                        }`}
                      >
                        <span>{isLinked ? 'Reload Plan' : '1-Click Proposal'}</span>
                        <ArrowRight className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Modal Footer */}
        <div className="p-4 border-t border-gray-100 dark:border-slate-800/80 bg-slate-50/50 dark:bg-slate-900/50 flex items-center justify-between shrink-0">
          <span className="text-xs text-gray-400">
            Powered by Tripbone AI Lead Capture Engine
          </span>
          <button
            type="button"
            onClick={onClose}
            className="px-4 py-1.5 rounded-xl border border-gray-200 dark:border-slate-700 text-xs font-bold text-gray-600 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-slate-800 cursor-pointer"
          >
            Close
          </button>
        </div>
      </div>
    </div>
  );
};
